SELECT 
	CD_PROD AS 'ID_PROD',
	NM_PROD AS 'NOME_PRODUTO',
	CD_IDEN_PROD AS 'COD_POLIPARTES',
	CD_UNIDADE,
	NM_UNIDADE,
	SG_UNIDADE,
	VAL_PRECO,
	CASE WHEN LEN(COD_BARRAS) > 12 THEN SUBSTRING(COD_BARRAS,1,12) ELSE COD_BARRAS END AS 'COD_BARRAS'
INTO TMP_CARGA_PRODUTO_BEMATECH
FROM
	(
	SELECT --TOP 1000
		PROD.PROS_COD AS 'CD_PROD', 
		UPPER(DBO.FN_REMOVE_CARACTERES_ESPECIAIS(PROD.PROS_NOM_RED)) AS 'NM_PROD', 
		PROD.PROS_EXT_COD AS 'CD_IDEN_PROD',
		UNIDADE.UNIP_COD AS 'CD_UNIDADE',
		UNIDADE.UNIP_NOM AS 'NM_UNIDADE',
		UNIDADE.UNIP_ABR AS 'SG_UNIDADE',
		--PRECO.PROL_VAL_PRE AS 'VL_SELL_PRICE',
		(SELECT TOP 1 PRECO.PROL_VAL_PRE
			  				   FROM TCOM_PROLIS PRECO
							   WHERE PRECO.PROS_COD = PROD.PROS_COD
							   ORDER BY PRECO.PROL_DAT_ALT DESC, PRECO.PROL_DAT_CAD
							   ) AS VAL_PRECO,
		CAST(CAST(PROD.PROS_BAR AS BIGINT) AS VARCHAR) AS 'COD_BARRAS'
		--PROD.PROS_BAR,
		--PROD.*
	FROM 
		TCOM_PROSER PROD 
		--INNER JOIN TCOM_PROLIS PRECO ON PROD.PROS_COD = PRECO.PROS_COD
		INNER JOIN TCOM_UNIPRO UNIDADE ON UNIDADE.UNIP_COD = PROD.UNIP_COD
	WHERE 
		  /*PRECO.PROL_DAT_ALT = (SELECT MAX(PRECO2.PROL_DAT_ALT) 
		   					    FROM TCOM_PROLIS PRECO2
								WHERE PRECO2.PROS_COD = PRECO.PROS_COD)
		  AND*/ PROD.PROS_DAT_FIM IS NULL
		  --AND PROD.PROS_EXT_COD = '4182162'
		  --AND PROD.PROS_COD = 4238
		  --AND ISNUMERIC(PROD.PROS_BAR) = 0
		  --AND PRECO.PROL_COD = PRECO.PROS_COD
	) AS TB_AUX
ORDER BY
	1 
	
	
--DROP TABLE TMP_CARGA_PRODUTO_BEMATECH
/*

SELECT * FROM TMP_CARGA_PRODUTO_BEMATECH WHERE ID_PROD IN (5375,5373,4804)
6087


SELECT * FROM TCOM_PROLIS PRECO WHERE PRECO.PROS_COD = 3 

SELECT PROD.PROS_COD, (SELECT TOP 1 PRECO.PROL_VAL_PRE
			  		   FROM TCOM_PROLIS PRECO
					   WHERE PRECO.PROS_COD = PROD.PROS_COD
					   ORDER BY PRECO.PROL_DAT_ALT DESC, PRECO.PROL_DAT_CAD
					   ) AS PRECO
FROM TCOM_PROSER PROD 
WHERE PROD.PROS_DAT_FIM IS NULL
ORDER BY 1

SELECT * FROM TCOM_PROLIS PRECO WHERE PROL_DAT_ALT = (SELECT MAX(PRECO2.PROL_DAT_ALT) 
			  										  FROM TCOM_PROLIS PRECO2
													  WHERE PRECO2.PROS_COD = PRECO.PROS_COD)




SELECT TOP 10 * FROM dbo.TCOM_KITPRE	
*/