IF EXISTS (SELECT * 
	   FROM   sysobjects 
	   WHERE  name = 'FN_REMOVE_CARACTERES_ESPECIAIS')
    DROP FUNCTION FN_REMOVE_CARACTERES_ESPECIAIS
GO

CREATE FUNCTION FN_REMOVE_CARACTERES_ESPECIAIS (@P_TEXTO VARCHAR(100))
RETURNS VARCHAR(100)
AS
BEGIN

-- DECLARA VARIÁVEIS
DECLARE @VARIAVEL VARCHAR(100)

-- REMOVE CARACTERES ESPECIAIS
	SELECT @VARIAVEL = @P_TEXTO
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ã','A')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Õ','O')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ã','A')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Õ','O')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ü','U')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ü','U')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Â','A')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ê','E')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Î','I')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ô','O')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Û','U')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Â','A')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ê','E')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Î','I')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ô','O')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Û','U')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ç','C')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'À','A')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'À','A')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Á','A')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'É','E')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Í','I')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ó','O')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ú','U')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ç','C')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Á','A')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'É','E')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Í','I')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ó','O')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'Ú','U')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'(','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,')','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'*','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'&','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'%','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'$','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'#','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'@','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'/','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'\','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,':','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,',','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'.','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,';','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'?','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'[','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,']','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'{','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'}','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'-','_')
	
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'"','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'!','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'''','_')
	SELECT @VARIAVEL = REPLACE(@VARIAVEL ,'`','_')
	
	RETURN RTRIM(LTRIM(@VARIAVEL))

	END

GO

/*

	SELECT DBO.FN_REMOVE_CARACTERES_ESPECIAIS('PRIMEIRA PROTEÇÃO   ') 

*/